//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kaskad
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id { get; set; }
        public string producttitle { get; set; }
        public string quantityofgoods { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<int> imageID { get; set; }
    
        public virtual Image Image { get; set; }
    }
}
